# Generated by Django 4.2 on 2025-09-07 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import parler.models


def copy_question_text_to_translation(apps, schema_editor):
    Question = apps.get_model("survey", "Question")
    QuestionTranslation = apps.get_model("survey", "QuestionTranslation")
    default_lang = settings.LANGUAGE_CODE
    for question in Question.objects.all():
        QuestionTranslation.objects.create(
            master_id=question.id,
            language_code=default_lang,
            text=question.text_old,
        )


def copy_question_text_to_old(apps, schema_editor):
    Question = apps.get_model("survey", "Question")
    QuestionTranslation = apps.get_model("survey", "QuestionTranslation")
    default_lang = settings.LANGUAGE_CODE
    for question in Question.objects.all():
        translation = QuestionTranslation.objects.filter(
            master_id=question.id, language_code=default_lang
        ).first()
        if translation:
            question.text_old = translation.text
            question.save(update_fields=["text_old"])


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="text",
            new_name="text_old",
        ),
        migrations.AlterField(
            model_name="question",
            name="text_old",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name="QuestionTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("text", models.CharField(max_length=500)),
                (
                    "master",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="survey.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "question Translation",
                "db_table": "survey_question_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.RunPython(
            copy_question_text_to_translation,
            reverse_code=copy_question_text_to_old,
        ),
    ]

